      MODULE REAL_PRECISION  ! HOMPACK90 module for 64-bit arithmetic.
      INTEGER, PARAMETER:: R8=SELECTED_REAL_KIND(13)
      INTEGER, PARAMETER:: I8=SELECTED_INT_KIND(13)
      END MODULE REAL_PRECISION
